name: notesharingappmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
  path_provider: ^2.0.15
  cached_network_image: ^3.3.1
  flutter_pdfview: ^1.3.1
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
